management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  servlet:
    context-path: /CustomerRelationShipManager

spring:
  application:
    name: CustomerRelationshipManager

  # Common JPA/Hibernate Configuration (shared across all environments)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: local # Default active profile
---
# Local Profile Configuration
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/CustomerRelationshipManager
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

---
# Development Profile Configuration
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/dev-db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

---
# Staging Profile Configuration
spring:
  config:
    activate:
      on-profile: stg
  datasource:
    url: jdbc:postgresql://stg-db-server:5432/stg-db
    username: stg_user
    password: stg_password
    driver-class-name: org.postgresql.Driver

---
# Production Profile Configuration
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/prod-db
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver